### ISSUE TITLE
[Script] - Automate Data Transfer from Rust Outputs to Cairo Constants

### ISSUE THREAD

**Issue by julienbrs** [julienbrs/Offsetter-merkle-tree#1]
## **Description**

Currently, the `.txt` files generated by the Rust code in `merkle_tree_rust/data/` need to be manually converted into `merkle_tree_cairo/tests/constants.cairo` for use in Cairo tests. This task aims to automate the process by creating a script that reads `.txt` files and generates a properly formatted `constants.cairo` file.

**Acceptance Criteria**
- [ ] Develop a script (Python appreciated, or Bash) that reads `.txt` files in the `output` directory and extracts. Use of decorator possible
- [ ] The script should generate a `constants.cairo` file in `merkle_tree_cairo/tests`.
- [ ] Ensure the script supports first and second waves of allocations.
- [ ] Document the process in `README.md`, including how to run the script.

**Additional Context**
- The generated constants should align with the format currently used in `merkle_tree_cairo/tests/constants.cairo`.
- The script should handle errors gracefully (e.g., missing files or invalid formats).
- [Medium Difficulty - Python/Bash]

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Josh-121) looking to make first contribution on this project. I have extensive experience in automation, python & bash/shell scripts

How I plan on tackling this issue
I have a good understanding on this issue and would ensure meeting the stated requirements.  I would also work on feedback & recommendation ensuring contact. Can deliver within a day upon assignment

**Comment by julienbrs** [comment]
Hi @Bosun-Josh121, I'm assigning you to this,  please join TG to discuss about it if needed: https://t.me/carbonableOD
please tag me if needed

**Comment by Bosun-Josh121** [comment]
> Hi @Bosun-Josh121, I'm assigning you to this, please join TG to discuss about it if needed: https://t.me/carbonableOD please tag me if needed

Noted. Thanks for the opportunity
