### ISSUE TITLE
[DevOps] - Setup Continuous Integration (CI/CD) for Rust and Cairo

### ISSUE THREAD

**Issue by julienbrs** [julienbrs/Offsetter-merkle-tree#2]
## **Description**

To ensure code quality and prevent regressions, a CI/CD pipeline should be implemented for both Rust and Cairo. The pipeline will run tests and perform linting/formatting checks on every push or pull request.

## **Acceptance Criteria**
- [ ] Configure GitHub Actions to run Rust tests (`cargo test`) and Cairo tests (`scarb test`) for all pushes and pull requests.
- [ ] Integrate formatting checks and linting for Rust code
- [ ] Integrate linting for Cairo code
- [ ] Add badges to the `README.md` for build status and test coverage.
- [ ] 

## **Additional Context**
- Use GitHub Actions workflows for automation.
- Ensure the pipeline runs efficiently and does not block unnecessarily long.
- Please link in your PR the success of CICD in your fork

- [ **Medium Difficulty - DevOps** ]

**Comment by raizo07** [comment]
Could I be assigned to this? I'm a software developer with over four years of experience.


I've implemented CI/CD for a couple of projects on Starknet

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by mexes20** [comment]
May I pick this up? I have three years experience in Software development and have contributed to some projects on OD here.

ETA: 10 hours.

**Comment by julienbrs** [comment]
Hi, I'm assigning it to @raizo07 as he was the first one to ask. Please join TG to discuss about it if needed: https://t.me/carbonableOD
Issue might be reassigned during ODHack if the contributor drops the isue
You can tag me for any question on that issue

**Comment by Supa-mega** [comment]
Let me handle this issue!

**Comment by Kingsuite** [comment]
Let me handle this issue!

**Comment by raizo07** [comment]
Acknowledged @julienbrs

**Comment by Benjtalkshow** [comment]
Let me handle this issue please.
