### ISSUE TITLE
[Rust] - Expand and Improve Unit Tests for Rust Code

### ISSUE THREAD

**Issue by julienbrs** [julienbrs/Offsetter-merkle-tree#3]
**Description**

Improve the coverage and robustness of the Rust codebase by adding comprehensive unit tests. This issue combines testing for all core modules (`allocation.rs`, `node.rs`, `merkle_tree.rs`) and ensures functionality across edge cases.

**Acceptance Criteria**
- [ ] Add unit tests for `Allocation`:
  - Test `Allocation::to_felts()` for invalid addresses and timestamps.
  - Validate edge cases for `u64_to_felt()` (e.g., `0`, `u64::MAX`).
  - Ensure correct behavior of the `Hash` implementation for `Allocation`.

- [ ] Add unit tests for `Node`:
  - Test `Node::new_leaf()` with allocations containing valid and invalid data.
  - Test combining identical leaf nodes using `Node::new()`.
  - Validate behavior when creating a parent node with an odd number of leaves.

- [ ] Add unit tests for `MerkleTree`:
  - Test `build_address_calldata()` for allocations with invalid formats (e.g., non-hex addresses).
  - Validate `merge_merkle_trees()` with empty trees and overlapping allocations.
  - Ensure correct handling of odd numbers of leaves in `MerkleTree::new()`.

**Additional Context**
- Tests should cover standard, edge, and error cases.
- Ensure all tests pass with `cargo test`.

[Medium Difficulty - Rust]

**Comment by codebestia** [comment]
Mind if I try this one?

**Comment by codeZe-us** [comment]
Can I work on this?
ETA: 7 hours

**Comment by mexes20** [comment]
I’d like to help with this.May I pick this up? I have three years experience in Software development and have contributed to some projects on OD here.

I'll write the proper tests and make sure the cover all edge cases and pass when run using cargo test

ETA: 10 hours.

**Comment by CollinsC1O** [comment]
Hello @julienbrs I'm a front-end and a blockchain developer I'd love to work on this.

**Comment by manlikeHB** [comment]
Hi, I am a Cairo & Rust developer and a returning contributor. I would love to work on this.

**Comment by julienbrs** [comment]
Hi, I'm assigning it to @codebestia as he was the first one to ask, please tag me if needed. Please join TG to discuss about it if needed: https://t.me/carbonableOD
Issue might be reassigned during ODHack if the contributor drops the isue

**Comment by Supa-mega** [comment]
Let me try this one!

**Comment by Unickhub** [comment]
Can I start working on this?

**Comment by Benjtalkshow** [comment]
Can I tackle this one?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Rust ,Cairo  projects like chainevents , arkprojects , starknet  etc  .   please /assign  this issue .
Thank You

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by kien6034** [comment]
m an experienced Rust developer with 4 year of experience, and recently have been doing a lot of rust open source contribution

https://github.com/paradigmxyz/reth/commits/main/?author=kien6034
https://github.com/foundry-rs/foundry/commits/master/?author=kien6034

How i plan?

- Review the codebase and implementation of Merkle Tree
- Add tests following the acceptance criteria 
- Will add more test cases if finding it necessary 

This should take 3 days of working in my estimation.
