### ISSUE TITLE
[Rust] - Add Comprehensive Integration Tests for Rust Code

### ISSUE THREAD

**Issue by julienbrs** [julienbrs/Offsetter-merkle-tree#4]
## **Description**

Develop integration tests to validate the interoperability between `allocation.rs`, `node.rs`, and `merkle_tree.rs` under realistic scenarios. The goal is to simulate and test real-world use cases, such as creating a Merkle tree and verifying proofs.

## **Acceptance Criteria**
- [ ] Write integration tests to validate full Merkle tree creation:
  - Use data from `mock_allocations_first_wave.json` and `mock_allocations_second_wave.json`.
  - Compare root hashes with expected values.
- [ ] Verify proofs generated by `build_address_calldata()`:
  - Validate the correctness of proofs using known allocations.
  - Test proof generation for invalid allocations and ensure graceful error handling.
- [ ] Simulate merging two trees:
  - Combine first and second wave allocations.
  - Validate the resulting tree's root hash and allocation integrity.

## **Additional Context**
- The tests should mimic real scenarios.
- Focus on end-to-end flows to catch potential integration bugs.

[Medium Difficulty - Rust]

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

I'm a member of **Dojo Coding** and have previously contributed to other projects like:

- `kakarot-rpc`
- `ef-tests`
- `kakarot-ssj`
- `Raito`
- `Starknet-Phone`

I'd like to work on this issue.

Check my OnlyDust profile for my contributions: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Understand the Codebase**:
   - Review `allocation.rs`, `node.rs`, and `merkle_tree.rs` to grasp their functionalities and interactions.
   - Familiarize myself with existing test setups and conventions.

2. **Set Up Test Environment**:
   - Ensure all dependencies are installed.
   - Prepare mock data using `mock_allocations_first_wave.json` and `mock_allocations_second_wave.json`.

3. **Write Integration Tests for Merkle Tree Creation**:
   - Use the mock data to create full Merkle trees.
   - Compare the generated root hashes with the expected values to validate correctness.

4. **Verify Proofs from `build_address_calldata()`**:
   - Write tests to validate proof correctness using known allocations.
   - Test with invalid allocations to ensure errors are handled gracefully.

5. **Simulate Merging Two Trees**:
   - Combine allocations from the first and second waves.
   - Create a merged Merkle tree and validate the root hash and allocation integrity.

6. **Run and Validate Tests**:
   - Execute all new and existing tests to ensure they pass.
   - Address any issues that arise during testing.

7. **Commit Changes** with a clear message


8. **Open a Pull Request** and await feedback.

---

**Comment by CollinsC1O** [comment]
Is it okay if I take this?

**Comment by julienbrs** [comment]
Hi, I'm assigning it to @martinvibes as he was the first one to ask, please tag me if needed. Please join TG to discuss about it if needed: https://t.me/carbonableOD
Issue might be reassigned during ODHack if the contributor drops the issue.

**Comment by petersdt** [comment]
May I pick this up?

**Comment by Unickhub** [comment]
May I try my hand at this?

**Comment by Supa-mega** [comment]
Can I work on this, please?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by JoE11-y** [comment]
I'd like to handle this task.

**Comment by Benjtalkshow** [comment]
Can I take this issue?

**Comment by TropicalDog17** [comment]
Hi, I have experience in various open source Rust projects and also previously work on a Carbonable issue.

https://github.com/carbonable-labs/svgenerator/pull/10

https://github.com/paradigmxyz/reth/commits/main/?author=TropicalDog17

https://github.com/foundry-rs/foundry/commits/master/?author=TropicalDog17

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Rust ,Cairo  projects like chainevents , arkprojects , starknet  etc  .   please /assign  this issue .
Thank You

**Comment by 0xDeon** [comment]
Could I grab this task?
How I hope to tackle this

- Write integration tests combining allocation.rs, node.rs, and merkle_tree.rs.

- Use mock JSON files for realistic Merkle tree creation; compare root hashes to expected values.

- Validate proofs from build_address_calldata() for both valid and invalid cases.

- Simulate merging two trees; ensure correct root hash and allocation consistency.

- Mimic end-to-end flows to catch integration issues.

ETA: 48 hrs
